Repository Kanav-Arora/tripzip, pull requests merged in 2024-04, with the labels that each got.

#90 Notification center
  backend/config.js
  backend/controllers/trips/create.controller.js
  backend/controllers/user/create.controller.js
  backend/controllers/user/fetch.controller.js
  backend/models/trip.mongo.js
  backend/package.json
  backend/routes/trips.js
  backend/utils/Novu/novuSubscriber.js
  backend/utils/Novu/novuTrigger.js
  frontend/package.json
  frontend/src/assets/ext-icon.jsx
  frontend/src/modules/NavBar/AuthContainer/AuthContainer.js
  frontend/src/modules/NavBar/NotificationCenter/NotificationCenter.js
  frontend/src/pages/Trip/Trip.js
  frontend/src/pages/Trip/components/TripBody/RequestCard.js
  frontend/src/pages/Trip/components/TripBody/TripBody.js
  package.json
Labels: work in progress

#105 Delete Account from Settings
  backend/controllers/user/create.controller.js
  backend/controllers/userDetails/delete.controller.js
  backend/controllers/userDetails/fetch.controller.js
  backend/routes/userDetails.js
  frontend/src/pages/AccountSetting/Components/DeleteAccountModal/DeleteAccountModal.js
Labels: pr: author review

#100 Centered the Header
  frontend/src/pages/NavBar/NavBar.js
  frontend/src/pages/NavBar/Styles.js
Labels: pr: under review
